### ISSUE TITLE
Change log level to Debug

### ISSUE THREAD

**Issue by ralphg6** [bancodobrasil/gin-telemetry#4]
Change log level to Debug

https://github.com/bancodobrasil/gin-telemetry/blob/424d18b77d8a523028761e0a23b050a27d3bcbc4/telemetry.go#L39

https://github.com/bancodobrasil/gin-telemetry/blob/424d18b77d8a523028761e0a23b050a27d3bcbc4/telemetry.go#L45

**Comment by matheusromano** [comment]
@ralphg6 ja pode fechar essa issue #6
